# Generated by Django 3.0.4 on 2020-03-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('zipcode', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('hours', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('stars', models.FloatField()),
                ('review_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=64)),
                ('category', models.IntegerField(choices=[(0, 'Burger'), (1, 'Pizza'), (2, 'Salad')])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.Restaurant')),
            ],
        ),
    ]
