# Generated by Django 3.0.4 on 2020-03-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='lng',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='zipcode',
            new_name='post_code',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
