# Generated by Django 3.0.4 on 2020-03-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200328_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='post_code',
            new_name='postal_code',
        ),
    ]
