# Generated by Django 3.0.4 on 2020-03-29 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200328_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='prob_burger',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='prob_pizza',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='prob_salad',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='food.Restaurant'),
        ),
    ]
